# Generated by Django 3.2 on 2026-02-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0006_alter_customuser_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='subject_total_marks',
            field=models.FloatField(default=100),
        ),
    ]
