# Generated by Django 3.2 on 2026-02-25 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0007_studentresult_subject_total_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_fee',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='FeePaymentHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount_paid', models.FloatField(default=0)),
                ('payment_method', models.CharField(default='Cash', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.students')),
            ],
        ),
        migrations.CreateModel(
            name='CertificateApplication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('certificate_type', models.CharField(max_length=255)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.students')),
            ],
        ),
    ]
