# Generated by Django 3.0.7 on 2026-06-18 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0009_auto_20260618_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeSetting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('college_name', models.CharField(max_length=255)),
                ('college_short_name', models.CharField(max_length=50)),
                ('college_logo', models.FileField(blank=True, null=True, upload_to='college_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='college_setting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
