# Generated by Django 3.0.7 on 2026-06-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0010_collegesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
