# Generated by Django 3.0.7 on 2026-06-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0011_staffs_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='gender',
            field=models.CharField(default='', max_length=50),
        ),
    ]
