# Generated by Django 3.0.7 on 2026-07-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0014_studentassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
